const { gql } = require("apollo-server");

export default gql`
  scalar DateTime

  type Account {
    id: String
  }
  type Transaction {
    id: Int
    title: String
    description: String
    amount: Float
    fromAccount: String
    toAccount: String
    transactionDate: DateTime
  }

  # All fields are required - id will be autogenerated by the system
  input AddTransactionInput {
    description: String!
    title: String
    amount: Float!
    fromAccount: String!
    toAccount: String!
  }

  # All fields besides id are optional, since this is a patch operation
  input UpdateTransactionInput {
    title: String
    description: String
    amount: Float
    fromAccount: String
    toAccount: String
  }

  type Query {
    accounts: [Account]
    transactions: [Transaction]
  }
  type Mutation {
    addTransaction(transaction: AddTransactionInput!): Transaction
    updateTransaction(
      id: Int!
      transaction: UpdateTransactionInput!
    ): Transaction
    deleteTransaction(id: Int!): Int
  }
`;
